### ISSUE TITLE
Can't create proper user when attaching a schema to Meteor.users

### ISSUE THREAD

**Issue by zeflash** [ignacy130/yadmin#5]
Hey, I'm desperately trying to get a grip on how this whole thing works.
The coffee script version works fine - but it uses outdated packages. I'm trying this one - via the "bootstrap" demo project - but I have multiple issues.

1) whenever I attach a Schema, the create account step (be it with register or from within the admin new user page) generates a user in the db which doesn't have emails in the usual email array.
The schema:
```javascript
Schemas.Users = new SimpleSchema({
  createdAt: {
    type: Date,
    label: "Creation date"
  },
  // admin stuff
  emails: {
    optional: true,
    type: Object,
    blackbox: true
  },
  // "emails.$.address": {
  //   optional: true,
  //   type: String,
  //   regEx: SimpleSchema.RegEx.Email
  // },
  // "emails.$.verified": {
  //   optional: true,
  //   type: Boolean
  // },
  profile: {
    type: Object,
    optional: true,
    blackbox: true
  },
  services: {
    type: Object,
    optional: true,
    blackbox: true
  },
  roles: {
    type: Object,
    optional: true,
    blackbox: true
  }
});

Meteor.users.attachSchema(Schemas.Users);
```

The resulting user:
```json
{
    "_id" : "b35XdCHpAAhrFemBq",
    "createdAt" : ISODate("2017-11-13T17:40:09.503Z"),
    "services" : {
        "password" : {
            "bcrypt" : "$2a$10$w1zSa0o6gnq4z5sLkxEX4u5.ce/cELvM1VMWWKyTuhtkPs4JEStRG"
        }
    },
    "emails" : []
}
```
As you can see, emails is empty, which breaks a lot of things and obviously the user can't log in. I haven't changed anything in the login/register code, it's using the default accounts-base + accounts-password packages.
If I don't attach a schema to the user, I can't add the fields I need on the users, but registration works. If I attach the schema, I can't create new users but I see the fields I want in the user editing page...

Given it works in yogiben coffee script earlier version, I suspect it has to do with the usage of collection2-core + the external npm simple-schema.

2) I don't see the user widget (is it adminUserWidget?) showing on the right side, I can only see the users in the left sidebar. Wondering why, but not critical at all

Any help would be greatly appreciated!

**Comment by zeflash** [comment]
As stated in the SimpleSchema issue I also reported, I figured I had to define more stuff in the Schema for the emails to be created properly.

This works:
```
  emails: {
    type: Object,
    optional: true,
  },
  'emails.$': {
    type: Object,
  },
  'emails.$.address': {
    type: String,
  },
  'emails.$.verified': {
    type: Boolean,
  },
```

As usual, after looking at the solution I feel stupid.

**Comment by ignacy130** [comment]
Glad you resolved this issue, tbh I had the same problem at one point ;)
